= Politicia Sports Rest API Document
yanychoi.github.io
:doctype: book
:icons: font
:source-highlighter: highlightjs // 문서에 표기되는 코드들의 하이라이팅을 highlightjs를 사용
:toc: left // toc (Table Of Contents)를 문서의 좌측에 두기
:toclevels: 2
:sectlinks:

[[User-API]]
== User API

[[User-Create]]
=== User POST
operation::user-create[snippets='http-request,http-response']

[[User-Read]]
=== User GET
operation::user-get[snippets='http-request,path-parameters,http-response,response-fields']

[[Post-API]]
== Post API

[[Post-Create]]
=== Post POST
operation::post-post[snippets='http-request,http-response']

[[Post-Read]]
=== Post GET
operation::post-get-single[snippets='http-request,path-parameters,http-response,response-fields']

[[Post-Update]]
=== Post PATCH
operation::post-patch[snippets='http-request,path-parameters,http-response']

[[Post-Delete]]
=== Post DELETE
operation::post-delete[snippets='http-request,path-parameters,http-response']

== Media API

[[Media-Create]]
=== Media POST
operation::media-post[snippets='http-request,http-response']

[[Media-Read]]
=== Media GET
operation::media-get[snippets='http-request,path-parameters,http-response,response-fields']

[[Media-Delete]]
=== Media DELETE
operation::media-delete[snippets='http-request,path-parameters,http-response']

[[Comment-API]]
== Comment API

[[Comment-Creation]]
=== Comment POST
operation::comment-post[snippets='http-request,http-response']

[[Comment-Edit]]
=== Comment PATCH
operation::comment-patch[snippets='http-request,http-response']

[[Comment-Deletion]]
=== Comment DELETE
operation::comment-delete[snippets='http-request,path-parameters,http-response']

[[Comment-Get]]
=== Comment GET
operation::comment-get[snippets='http-request,path-parameters,http-response,response-fields']

